export const APP_NAME = 'Igniteway'
export const PERSIST_STORE_NAME = 'admin'
export const REDIRECT_URL_KEY = 'redirectUrl'
// export const BASE_URL = 'http://localhost:4000/api'
export const BASE_URL = 'http://ec2-43-204-2-117.ap-south-1.compute.amazonaws.com/api'
